### PR TITLE
[#35] Ensures pre_request hook happens before the response is invoked

### PR DESCRIPTION
**Pull request by kentontaylor**

### CODE REVIEW

**Comment by brondsem** [comment]
This change looks good to me, seems to work correctly now.

Looks like travis failed only on the `example/tests.py` which is Selenium tests which isn't too surprising (although it passed last time, quite a while ago).  

@kadams54 any thoughts?

**Comment by kadams54** [comment]
Yeah, looks like there may be some config askew on the CI build. I'll look at getting that green then this has my :+1: to land.

**Comment by brondsem** [comment]
Seems unrelated to me, so I've created #37 for the selenium issue.

I'd like to merge this change and cut a release with it.

**Comment by kadams54** [comment]
Will do.

**Pull request merged**
